apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: docker.io/cyrildiagne/u2net-http
    docker:
      dockerfile: ./Dockerfile
deploy:
  kubectl:
    manifests:
      - deploy/service.yaml
